<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<RootNamespace>LR1</RootNamespace>
		<AssemblyName>LR1</AssemblyName>
		<ApplicationHighDpiMode>DpiUnaware</ApplicationHighDpiMode>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LR1.Tests" />
	</ItemGroup>
</Project>