<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="MSTest.TestAdapter" Version="3.1.1"/>
        <PackageReference Include="MSTest.TestFramework" Version="3.1.1"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\LR1\Order.cs" Link="Order.cs" />
        <Compile Include="..\LR1\OrderStatus.cs" Link="OrderStatus.cs" />
        <Compile Include="..\LR1\OrderManager.cs" Link="OrderManager.cs" />
        <Compile Include="..\LR1\Form1.cs" Link="Form1.cs" />
        <Compile Include="..\LR1\Form1.Designer.cs" Link="Form1.Designer.cs" />
    </ItemGroup>

</Project>
